command /test <text>:
 trigger:
  if arg-1 is "save":
   if target block of player is a chest:
    send "&aSaving inventory"
    delete {SavedInv::%player%::*}
	loop items in inventory of target block of player:
	 add loop-item to {SavedInv::%player%::*}
	 if arg-1 is "load":
	  open chest inventory with 6 row to player 
      set {_glass} to white glass pane named "0"
      set {_i} to 0
      loop 54 times:
       set slot {_i} of player's current inventory to {_glass}
       add 1 to {_i}
      set slot 13 of player's current inventory to air
      set slot 22 of player's current inventory to air
      set slot 31 of player's current inventory to air
      set slot 40 of player's current inventory to air
      set slot 53 of player's current inventory to barrier
	  add {SavedInv::%player%::*} to current inventory of player