on right click:
    if player's tool is saddle:
        spawn horse at player
        add "{Variant:259,SaddleItem:{id:saddle,Count:1},Age:0}" to last spawned entity's nbt
        apply speed 1 to spawned entity for 1 minute
        tame last spawned entity to player
        make player ride spawned horse
On Vehicle Exit:
 loop 2 times:
  loop living entities in radius 5 of player:
  loop entity is horse
   kill loop entity
on death of a horse:
 clear drops
